apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: rkvishnu77/flask-app
    argocd-image-updater.argoproj.io/image-update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: rkvishnu77/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
