name: Build and Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: rkvishnu77
        password: something

    - name: Build Docker image
      run: |
        docker build -t rkvishnu77/flask-app:latest .
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push rkvishnu77/flask-app:latest

 