name: Build and Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: rkvishnu77
        password: something


    - name: Build and Push Docker image
      run: |
        docker build -t rkvishnu77/flask-app:latest -t rkvishnu77/flask-app:${{ github.sha }} .
        docker push rkvishnu77/flask-app:${{ github.sha }}
        docker push rkvishnu77/flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 3: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    # Step 4: Update kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name flask-app-cluster1

    # Step 5: Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/
